# Programming for AI & Data Science

## Workshop 3

## File IO, CSV, and JSON File Formats
________________________________________

## Aims of the workshop

Last week we looked at functions and classes, and how we might build up our repertoire of code into reusable sections using these concepts, as well as break down problems into smaller, easier to manage, sub-problems. An example of this was an exercise from last week where we converted grades into classifications, whereby we can build a simple function which takes one number, and produces one string. Using our knowledge of list comprehensions we can simply apply this basic function to each element of grades.

This week, we’ve looked at File Input & Output, looking at how Python can interact with any operating system which is running it (Windows/Mac/Linux) and manipulate files with reading and writing (or both). We explored how we might save data to files such that it can be easily understood by other parties, and why data formats are beneficial in this regard. Notable examples of this were the Comma-Separated Values (CSV) and Javascript Object Notation (JSON) data formats.
Along the way we also introduced some new vocabulary, and keywords such as context managers (using the with keyword), as well as continue (used in for loops).

In this workshop, we will also briefly consider Numpy which is a library for numerical computing within Python. These are used to provide some nice functionality for calculation purposes. Most of the numerical computing within python either uses this directly, or builds on-top of it.

Please see ‘Useful Information’ below on how to lookup certain Python functionality. The concept behind this workshop is about discovery, and experimentation surrounding topics covered so far.

Feel free to discuss the work with peers, or with any member of the teaching staff.

----

## File IO

For this workshop, as always, save a copy of the completed notebook. Name this something memorable.
E.g “Workshop 3”

## Reading Files

### Exercise 1
Create a text file in the same directory as your python notebook for this workshop session. Fill this text file with content of your choice. These could be your favourite song lyrics. Dear Theodosia from Hamilton will be my choice here.
Name this file __ex1_data.txt__.

Note: I will upload my ex1_data.txt with my “Dear Theodosia” lyrics to Canvas if you wish to follow along with my examples.

Example:
> ```
Dear Theodosia, what to say to you?
You have my eyes
You have your mother's name
When you came into the world, you cried and it broke my heart
I'm dedicating every day to you
Domestic life was never quite my style 
...


At the moment, we are not interested in the format of what is in the file. Just the raw text within it.

---

---
### Exercise 2
In our Workshop 3 Notebook, let’s open this file, and get Python reading this data in.

From the lectures, we know that we can use `open()` to open any file path we provide. Remember, `open()` returns a file object itself. Assign this to a sensibly named variable. For now, we will specify the file path as the <u>local file path</u>, and we will explicitly pass the argument `mode='r'` even though this is the default value.

Once we have this assigned to a variable, we can print the type of the variable (it’s an object), to see what it is.
```
my_file = open('ex1_data.txt', mode='r')
print( my_file )
print( type(my_file) )
```
This should look something similar to the following:
 
> ```
<_io.TextIOWrapper name='ex1_data.txt' mode='r' encoding='cp1252'>
<class '_io.TextIOWrapper'>
> ```

__Additionally__, try replacing the `'ex1_data.txt'` with the full path equivalent instead. For me this might look like `'/home/cssbct/Documents/Data Science/Wk3/Workshop/ex1_data.txt'` and yours may look like `'C:/Users/...'` etc. This depends on your Operating System (Windows/Mac/Linux). Re-run the cell and make sure it also works.

---


In [1]:
my_ext_file = open('ext_1.txt', mode='r')
print(my_ext_file)
print(type(my_ext_file))

<_io.TextIOWrapper name='ext_1.txt' mode='r' encoding='cp1252'>
<class '_io.TextIOWrapper'>


---
### Exercise 3
Let’s read some data out from this file object. We can use a `for` loop which iterates directly over lines in the file itself.
For each line in the file, print the line.
```
for line in my_file:
    print(line)
```
> Dear Theodosia, what to say to you?  
You have my eyes  
You have your mother's name  
 
__Note__: If things don’t seem to print, read the beginning of Ex 4 and it might make sense.

---

In [7]:
for line in my_ext_file:
    print(line)

---
### Exercise 4
Execute the `for` loop again.
We have a problem with the previous exercise. If we try and execute the `for` loop again, just printing the line, we won’t get anything out! 
```
for line in my_file:
    print(line)
```
> 

This is because we’ve already hit the end of the file. Python is doing some ‘tracking’ in the background which keeps track of where in the file we are. As we already hit the end of the file by iterating over it with Exercise 3, when we try to iterate again, no new lines have been added. Thus printing nothing!
This isn’t ideal. So every time we want to iterate through the file here, we need to reopen the file!

Combine the Notebook cell which opens the file, with the iterating code from Exercise 3. From the lecture’s this week, we also know that it’s important to <u>close</u> a file once we’ve finished with it. So let’s also add that to the end.

__To Merge cells__: Select a Cell, go to Edit -> Merge Cell (Above/Below).

Once this is done we should have something which looks like the following: 
```
my_file = open('ex1_data.txt', mode='r')
print( my_file )
print( type(my_file) )

for line in my_file:
    print(line)
    
my_file.close()
```
This is good, as we know all of that code will execute in-order, at once. If they are in separate notebook cells we can technically execute them in any order! Now this cell will open, read, and close the file.

---

In [8]:
my_ext_file = open('ext_1.txt', mode='r')
for line in my_ext_file:
    print(line)
    
my_ext_file.close()

Dear Theodosia, what to say to you?

You have my eyes

You have your mother's name

When you came into the world, you cried and it broke my heart

I'm dedicating every day to you

Domestic life was never quite my style


---
### Exercise 5
Now that we have everything together, and it’s not going to behave strangely when printing lines, we can begin to change our simple print expression to something more complex.

We can search for strings within other strings by executing the following boolean expression:
```
<string> in <other string> 
```
E.g.: In my example, I want to check if the line we’re checking contains the word Theodosia.
Note: `“theodosia” != “Theodosia”` (Capital letters are different to lowercase in programming!).
```
if "Theodosia" in line:
    	print("Found!")
```        
If I execute this cell again, it should open the file, iterate through it, and print “Found her!” for the line in which this comes up.

> #### Found!
 
Depending on what is in your text document, search for some string which is present.

----

In [9]:
my_ext_file = open('ext_1.txt', mode='r')
for line in my_ext_file:
    if "world" in line:
        print("Found!")
    
my_ext_file.close()

Found!


---
### Exercise 6
This isn’t very useful either. I want to know the line number where this lyric comes up. We can use enumerate, covered in previous workshops, to provide line numbers alongside the elements themselves.

1.	Modify your for loop to use enumerate which is passed your file object.
2.	Replace your print statement, to now print the line numbers which your string appears.

> __Found! At:   0__
 
In my example, Theodosia only appears once, on line 0 (the first line).
If I wanted to find a more common word. I’m going to search for “We”.

> __Found! At:   9__  
> __Found! At:  11__   
> __Found! At:  32__  
> __Found! At:  34__  

Note: I can call the function `lower()` on a string to convert it all to lowercase. This might make checking easier. I can check for “We” and “we” with a single check now.

Example:
```
if "we" in line.lower():
    	print("Found! At: ", line_no)
```
I’ve now found some more entries which I missed before! (I was only checking for “We” prior).

> __Found! At:   9__   
> __Found! At:  10__  
> __Found! At:  11__  
> __Found! At:  26__  
> __Found! At:  32__  
> __Found! At:  33__  
> __Found! At:  34__   

---

In [16]:
my_ext_file = open('ext_1.txt', mode='r')
for i, line in enumerate(my_ext_file):
    if "you" in line.lower():
        print("Found at line:", i)
    
my_ext_file.close()

Found at line: 0
Found at line: 1
Found at line: 2
Found at line: 3
Found at line: 4


__Footnote about the end of lines in text files__. Many Python programmers need not know about this level of detail, but people who have programmed in other languages may be aware of the issue. Different Operating Systems denote the end of line in a text file in different ways. On linux and unix it is marked by a single `\n`; on MacOS it uses `\r` and on Windows it uses both as `\r\n`. Fortunately, when processing text files in Python the system conveniently presents all line ends as `\n` making the coding easier and more portable.

---
### Exercise 7
Instead of just printing the lines where we’ve found “we” (lowercase and uppercase variants), let’s append these lines to a fresh List.

1.	Create an empty list, giving it a suitable variable name. Make sure this is done before your for loop! Otherwise you’ll constantly make empty ones.
2.	If your chosen word is in the line, append the line to this List.
3.	After the file close line, print the List (both ways, see below).

We can see that it is indeed a List of strings:
 
> __Found! At:  34__   
> "We'll bleed and fight for you, we'll make it right for you\n", 'If we lay a strong enough foundation\n', "We'll pass it on to you, we'll give the world to you\n", 'I swear that\n', "We'll bleed and fight for you, we'll make it right for you\n", 'If we lay a strong enough foundation\n', "We'll pass it on to you, we'll give the world to you\n"]  

Or a nicer way, we can iterate through this List we made, and print each individual item:
 
> __Found! At:  34__  
> We'll bleed and fight for you, we'll make it right for you
>
> If we lay a strong enough foundation
>
>We'll pass it on to you, we'll give the world to you

---

In [17]:
my_ext_file = open('ext_1.txt', mode='r')
found_list = []
for i, line in enumerate(my_ext_file):
    if "you" in line.lower():
        found_list.append(line)
    
my_ext_file.close()
print(found_list)

['Dear Theodosia, what to say to you?\n', 'You have my eyes\n', "You have your mother's name\n", 'When you came into the world, you cried and it broke my heart\n', "I'm dedicating every day to you\n"]


---
### Exercise 8

Notice how we seem to be getting an extra space between prints. This is due to that “\n” which appears at the end - or rather, all of the \n. 

We can remove the trailing newlines and spaces by calling `rstrip()` on our strings. To prove this we can check the following:
```
nightmare = "This is excessive\n\n\n\n\n\n\n\n\n       	"
print(nightmare)
``` 

> This is excessive    
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  
>  &nbsp;  

Yes, that is a lot of blank space…
If we `print nightmare.rstrip()` it will return a string which is rid of those special characters and all the spaces! The original variable is __NOT__ modified.
```
print(nightmare,rstrip())
```

> This is excessive

It is immediately obvious that the newlines are gone (left), however, spaces are trickier. We can do some string concatenation if we really wanted to prove the spaces are also gone:
```
print(nightmare,rstrip() + "test")
```
> This is excessivetest

Note: The existence of `rstrip` does indeed suggest the existence of a normal `strip` function, as well as an `lstrip`. Feel free to look these up.

 
---

---
## Writing Files

### Exercise 9
In a new cell, we need to open a file to write. Let’s write to the same file we’ve been working with. This time we will specify `mode='w'`. We know we need to close the file, so let’s write that in at the bottom before we forget.
```
ex9_file = open('ex1_data_copy.txt', mode='w')
print( ex9_file )
print( type(ex9_file) )

# Do stuff

ex9_file.close() # Might as well write this in before we forget.
```
As before, we should see it’s a valid file, and the type is correct.

Even though we’ve not told Python to write anything, you may notice that a file has been created! It’s just empty.

---

In [18]:
my_ext_file = open('ext_1.txt', mode='w')
print( my_ext_file )
print( type(my_ext_file) )
my_ext_file.close()

<_io.TextIOWrapper name='ext_1.txt' mode='w' encoding='cp1252'>
<class '_io.TextIOWrapper'>


---
### Exercise 10
We can call `ex9_file.write()` passing it a string to write to the file. The behaviour of this depends on the file mode. In our case, we’re on write, which will erase any existing content with what we put, if the file doesn’t exist it will create it.

<u>Write some content to this file</u> by modifying the `#Do Stuff` section of our code.

After this open up the file and check what you intended to write. (Open in Notepad or Notepad++).

> ## We're taking the hobbits to Isengard!

----

In [ ]:
my_ext_file = open('ext_1.txt', mode='w')
my_ext_file.write("work while you, play while you play")
my_ext_file.close()

---
### Exercise 11
Some time later we realised that we missed off some information. Let’s append that to our file now.

1.	Open the file in append mode
2.	Create a List, and put some strings you want to write in it. (Note: These can also be numbers converted to strings - If we try numbers, we’ll get an error).
```
some_jibberish = ["Doe, a deer", "a female deer", "far", "a long long way to run!" ]
```
3.	Iterate through this list, and for each element write this to the file.
4.	Don’t forget to close the file!

Open your file once finished, and check if the original content is present, with your additions added to the bottom in sequence order.

> We're taking the hobbits to Isengard!Doe, a deera female deerfaralong long was to run!Doe, a deera female deerfara long long was to run!
 
5.	Whoops! They’re all on the same line in the file! Remember to add that special `\n` to each string you want to add! We can either change each string element literal. Or do some string concatenation in the write line itself!
    a.	E.g. Instead of `.write(s)` we can do `.write( s + "\n" )`. Saves us a lot of typing!

> We're taking the hobbits to Isengard!Doe, a deer  
a female deer  
far  
a long long was to run!

6.	Ahh! Almost. We need to make sure we write a newline at the end of the Exercise 9 bit, or before the first line written for this exercise. Try fixing this so you get the following output (swings and roundabouts on this one):
 
> We're taking the hobbits to Isengard!  
Doe, a deer  
a female deer  
far  
a long long was to run!

---

In [28]:
my_ext_file = open('ext_1.txt', mode='w')
something_extra = ["Doe, a deer\n", "a female deer\n", "far\n", "a long long way to run!" ]
for line in something_extra:
    my_ext_file.write(line)

f = open('ext_1.txt', mode='r')
for line in f:
    print(line)
f.close()

Doe, a deer

a female deer

far

a long long way to run!


---
### Exercise 12
In the lectures we introduced Context Managers. Let’s use those now.  
Recall:
```
f = open(..)
# Do stuff
f.close()
```
Becomes:
```
with open(..) as f:
	# Do Stuff.
```
Duplicate your solutions to the previous answers involving file opening, replacing the clunky open, and close mechanisms with some Context Managers.

---

In [29]:
with open('ext_1.txt') as f:
    for line in f:
        print(line)
        
f.close()

Doe, a deer

a female deer

far

a long long way to run!


---
### Exercise 13
Try the following in a new cell:
```
with open("./no_exist.txt") as f:
	pass
```
You should get the following output:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5680/3485904372.py in <module>
----> 1 with open("./no_exist.txt") as f:
      2         pass

FileNotFoundError: [Errno 2] No such file or directory: './no_exist.txt'
```
This week we also introduced `try` and `except` for helping with Error Handling which follows the following format:
```
try:
	# Do stuff here.
except:
	# Any Issues, do this block.
```
1.	Put the context manager, in its entirety, within the `try` block.
2.	Add a nice print message into the `except` block which alerts you that something happened.
```
try:
    with open("./no_exist.txt") as f:
        pass
except:
    print("Uh oh, we're in trouble.")
``` 

---

In [33]:
try:
    with open('./not_in_existence.txt') as f:
        pass
except:
    print('file not found')
        
f.close()







file not found


---
### Exercise 14
We can improve this, currently we have no idea what the error is.

Modify the `except` line to catch the general exception `Exception`. Using the `as` keyword, give it a useful name. Then use this in your `print` statement.

> Uh oh, we're in trouble. [Errno 2] No such file or directory: './no_exist.txt'

---

In [37]:
try:
    
    with open('./not_in_existence.txt') as f:
        pass
except Exception as e:
    print('oh, we are in trouble', e)
        
f.close()

oh, we are in trouble [Errno 2] No such file or directory: './not_in_existence.txt'


---
### Exercise 15
As we have already encountered this error, we can add a more specific except clause above the general one. Make this catch the `FileNotFoundError` exception, and get it to print something different.
```
except FileNotFoundError as not_found:
    print( "Didn't find the file, see message below" )
    print ( not_found )
```
> Didn't find the file, see message below  
> [Errno 2] No such file or directory: './no_exist.txt'
 

This try, except structure will prevent the whole of python from erroring out. Any code after this structure will continue to be executed as normal. If this code is unrelated then it will execute just fine. Be cautious of putting code outside this try structure, if it relates to what’s inside.

The behaviour of errors being swallowed by these `except` clauses is known as Error Hiding. 

---

---
## CSV
### Exercise 16
On canvas you will find a `wind_data.csv` file. Download this to the same directory as your python notebook. Just like the text files from earlier.

---

---
### Exercise 17
Import csv, and read the wind_data.csv file using a context manager. The file will be in ‘read’ mode.

Create a csv_reader, passing it the file we’ve just opened.

Print each line of this reader to see what data we’re dealing with.

---

In [38]:
import csv
with open('wind_data.csv') as my_file:
    csv_reader = csv.reader(my_file, delimiter=',')
    for line in csv_reader:
        print(line)

['ï»¿Date/Time', 'LV ActivePower (kW)', 'Wind Speed (m/s)', 'Theoretical_Power_Curve (KWh)', 'Wind Direction (Â°)']
['01 01 2018 00:00', '380.047790527343', '5.31133604049682', '416.328907824861', '259.994903564453']
['01 01 2018 00:10', '453.76919555664', '5.67216682434082', '519.917511061494', '268.64111328125']
['01 01 2018 00:20', '306.376586914062', '5.21603679656982', '390.900015810951', '272.564788818359']
['01 01 2018 00:30', '419.645904541015', '5.65967416763305', '516.127568975674', '271.258087158203']
['01 01 2018 00:40', '380.650695800781', '5.57794094085693', '491.702971953588', '265.674285888671']
['01 01 2018 00:50', '402.391998291015', '5.60405206680297', '499.436385024805', '264.57861328125']
['01 01 2018 01:00', '447.605712890625', '5.79300785064697', '557.372363290225', '266.163604736328']
['01 01 2018 01:10', '387.2421875', '5.30604982376098', '414.898178826186', '257.949493408203']
['01 01 2018 01:20', '463.651214599609', '5.58462905883789', '493.677652137077', '25

['23 01 2018 08:10', '193.35530090332', '10.2925796508789', '2961.00601117831', '24.509199142456']
['23 01 2018 08:20', '172.922698974609', '9.7607717514038', '2634.15690710322', '24.4146194458007']
['23 01 2018 08:30', '261.980590820312', '10.5749797821044', '3100.79220826264', '23.7484302520751']
['23 01 2018 08:40', '155.7958984375', '9.35851955413818', '2377.19410354324', '23.3566493988037']
['23 01 2018 08:50', '121.010398864746', '8.43222904205322', '1786.37057511023', '24.3038501739501']
['23 01 2018 09:00', '151.622100830078', '8.52264976501464', '1841.97916711166', '22.7741794586181']
['23 01 2018 09:10', '263.114685058593', '9.7986831665039', '2660.44001266753', '22.9170398712158']
['23 01 2018 09:20', '269.465698242187', '9.89809703826904', '2727.09638236781', '23.6632003784179']
['23 01 2018 09:30', '146.92919921875', '8.29679584503173', '1704.26160416832', '25.0993900299072']
['23 01 2018 09:40', '175.74690246582', '8.59385108947753', '1886.17616663223', '25.6650009155273'

['17 02 2018 12:20', '1291.62194824218', '7.42210483551025', '1217.93413419655', '40.0971717834472']
['17 02 2018 12:30', '1156.09204101562', '7.16875791549682', '1093.80274831431', '40.1519699096679']
['17 02 2018 12:40', '1193.86206054687', '7.24012517929077', '1127.85401560287', '48.6891784667968']
['17 02 2018 12:50', '1367.92199707031', '7.69425296783447', '1360.07346861044', '53.6613998413085']
['17 02 2018 13:00', '1771.24096679687', '8.29014587402343', '1700.2687929949', '57.0652809143066']
['17 02 2018 13:10', '1752.32897949218', '8.28145790100097', '1695.05800878786', '52.8902511596679']
['17 02 2018 13:20', '1196.04296875', '7.20628499984741', '1111.62092808699', '49.5069007873535']
['17 02 2018 13:30', '1070.09094238281', '6.96775007247924', '1001.53687094485', '46.1391716003417']
['17 02 2018 13:40', '1051.13793945312', '6.87271308898925', '959.703168003792', '45.6919708251953']
['17 02 2018 13:50', '1092.08605957031', '6.96966886520385', '1002.39305641504', '43.9093513488

['11 03 2018 19:10', '0', '2.91497206687927', '0', '267.6328125']
['11 03 2018 19:20', '0', '3.14850306510925', '22.5163509112435', '308.729705810546']
['11 03 2018 19:30', '0', '2.59195899963378', '0', '291.580505371093']
['11 03 2018 19:40', '0', '2.59379601478576', '0', '264.139190673828']
['11 03 2018 19:50', '0', '2.52590990066528', '0', '274.781005859375']
['11 03 2018 20:00', '0', '2.47656297683715', '0', '265.036590576171']
['11 03 2018 20:10', '0', '3.43928503990173', '45.4948289793729', '243.103897094726']
['11 03 2018 20:20', '43.3767700195312', '4.18930912017822', '158.972887392242', '240.696899414062']
['11 03 2018 20:30', '87.9892196655273', '4.17896795272827', '156.963487106514', '236.82209777832']
['11 03 2018 20:40', '389.466003417968', '5.79091787338256', '556.71215402901', '226.226699829101']
['11 03 2018 20:50', '364.336608886718', '5.46359682083129', '458.588580633461', '224.44400024414']
['11 03 2018 21:00', '105.294898986816', '4.08551502227783', '139.04144954314

['03 04 2018 15:40', '0', '3.57705903053283', '61.1056589546106', '44.1199302673339']
['03 04 2018 15:50', '65.7856903076171', '4.14307785034179', '150.030682166231', '46.237060546875']
['03 04 2018 16:00', '90.97119140625', '3.98662090301513', '125.445533397797', '42.1388397216796']
['03 04 2018 16:10', '191.768203735351', '4.62806892395019', '249.610821958281', '37.0694999694824']
['03 04 2018 16:20', '231.205200195312', '4.82174396514892', '293.385283718246', '38.7955284118652']
['03 04 2018 16:30', '140.813293457031', '4.29045295715332', '178.913914642402', '44.0763206481933']
['03 04 2018 16:40', '219.063003540039', '4.71068620681762', '267.976407142567', '50.63862991333']
['03 04 2018 16:50', '315.423706054687', '5.26363182067871', '403.504034223334', '46.4820709228515']
['03 04 2018 17:00', '202.338104248046', '4.64619398117065', '253.601878548515', '47.2567291259765']
['03 04 2018 17:10', '152.970901489257', '4.36679315567016', '194.32403578499', '49.9428596496582']
['03 04 201

['27 04 2018 18:20', '3383.2490234375', '12.4944601058959', '3578.71553428148', '65.075927734375']
['27 04 2018 18:30', '3142.90502929687', '12.3052597045898', '3561.63679963172', '68.2064208984375']
['27 04 2018 18:40', '3286.65600585937', '13.0226697921752', '3600', '70.0837631225585']
['27 04 2018 18:50', '3370.498046875', '12.5670099258422', '3583.79924177649', '68.4643020629882']
['27 04 2018 19:00', '2751.78002929687', '11.1253499984741', '3314.92675310118', '65.6252136230468']
['27 04 2018 19:10', '2890.205078125', '11.4221000671386', '3401.9688452893', '67.3756866455078']
['27 04 2018 19:20', '3369.94189453125', '12.6882400512695', '3590.52540152362', '74.4754562377929']
['27 04 2018 19:30', '3397.2548828125', '12.7492799758911', '3593.08680115431', '73.0031127929687']
['27 04 2018 19:40', '3425.6669921875', '12.7501697540283', '3593.12009244781', '72.1075134277343']
['27 04 2018 19:50', '3453.54809570312', '12.7536897659301', '3593.25065878321', '71.8102264404296']
['27 04 201

['20 05 2018 15:50', '1239.07104492187', '7.4629168510437', '1238.80414729079', '44.1715812683105']
['20 05 2018 16:00', '709.616088867187', '6.23532676696777', '706.296814098114', '48.3715209960937']
['20 05 2018 16:10', '546.400695800781', '5.97453880310058', '616.438257731428', '58.5945014953613']
['20 05 2018 16:20', '1004.58599853515', '7.29113006591796', '1152.62235477537', '58.7754402160644']
['20 05 2018 16:30', '1075.458984375', '7.44569587707519', '1229.96714690928', '58.67333984375']
['20 05 2018 16:40', '1080.47595214843', '7.4500880241394', '1232.21671365356', '60.2757606506347']
['20 05 2018 16:50', '1281.92297363281', '7.79913711547851', '1417.15496366794', '57.4432487487792']
['20 05 2018 17:00', '1299.43200683593', '8.10000038146972', '1587.77227989779', '62.0390815734863']
['20 05 2018 17:10', '1276.33703613281', '7.98113584518432', '1519.21252560507', '62.2034606933593']
['20 05 2018 17:20', '1204.23095703125', '7.81234884262084', '1424.43791945434', '60.041049957275

['16 06 2018 00:50', '1410.27001953125', '8.16267490386962', '1624.48431839809', '146.689804077148']
['16 06 2018 01:00', '2074.38598632812', '9.48426342010498', '2459.65619961211', '155.430892944335']
['16 06 2018 01:10', '1413.00500488281', '7.97285890579223', '1514.49259434049', '166.136306762695']
['16 06 2018 01:20', '1109.32995605468', '7.51178121566772', '1264.04917878144', '175.415603637695']
['16 06 2018 01:30', '894.873596191406', '7.10053014755249', '1061.89319494097', '178.958694458007']
['16 06 2018 01:40', '754.793212890625', '6.68113708496093', '878.687803699048', '182.975601196289']
['16 06 2018 01:50', '897.468688964843', '7.1499319076538', '1084.93584430521', '183.958206176757']
['16 06 2018 02:00', '977.119873046875', '7.48098993301391', '1248.12705878448', '178.698196411132']
['16 06 2018 02:10', '1349.86804199218', '8.41158866882324', '1773.76257158475', '170.461502075195']
['16 06 2018 02:20', '1343.40698242187', '8.330322265625', '1724.44858138209', '166.47810363

['14 07 2018 01:30', '928.928771972656', '7.06494188308715', '1045.49310477812', '17.6089496612548']
['14 07 2018 01:40', '1065.44799804687', '7.28941202163696', '1151.78209720783', '18.2995796203613']
['14 07 2018 01:50', '1104.12194824218', '7.42877292633056', '1221.32681582512', '17.2330493927001']
['14 07 2018 02:00', '1200.88195800781', '7.80156517028808', '1418.49190179547', '16.4476890563964']
['14 07 2018 02:10', '1179.66796875', '7.77033996582031', '1401.35143747897', '14.2307500839233']
['14 07 2018 02:20', '663.335815429687', '6.59292411804199', '842.821336097712', '19.8074607849121']
['14 07 2018 02:30', '573.609924316406', '6.17419910430908', '684.348527690823', '22.4313602447509']
['14 07 2018 02:40', '552.526611328125', '6.27280902862548', '719.953442538587', '21.3294105529785']
['14 07 2018 02:50', '730.029602050781', '6.68323183059692', '879.55034670071', '18.3976402282714']
['14 07 2018 03:00', '963.449584960937', '6.81553077697753', '935.064714337008', '27.1871109008

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



---
### Exercise 18
Extract the first line, as this contains the headers - Store this as a variable. Take note of the type of this line, compared to our lines from the raw file reading earlier in the workshop. What do you notice?

---

In [41]:
import csv
with open('wind_data.csv') as my_file:
    csv_reader = csv.reader(my_file, delimiter=',')
    for i, line in enumerate(csv_reader):
        if(i == 0):
            print(line)
            print(type(line))


['ï»¿Date/Time', 'LV ActivePower (kW)', 'Wind Speed (m/s)', 'Theoretical_Power_Curve (KWh)', 'Wind Direction (Â°)']
<class 'list'>


---
### Exercise 19

1.	Which index would we need to take to extract the “Wind Speed” attribute?
2.	For each line, obtain the Wind Speed (index the correct index).
3.	This will be a string! Convert/cast it to a float
4.	Append it to a list of wind speeds.

Note: Be careful not to include the headers in this! Just data values we want. Numbers to do analyses on.

```
print(speed)
```
 
---

In [46]:
import csv
speed = []
with open('wind_data.csv') as my_file:
    csv_reader = csv.reader(my_file, delimiter=',')
    for i, line in enumerate(csv_reader):
        if(i > 0):
            speed.append(float(line[2]))
print(speed)

[5.31133604049682, 5.67216682434082, 5.21603679656982, 5.65967416763305, 5.57794094085693, 5.60405206680297, 5.79300785064697, 5.30604982376098, 5.58462905883789, 5.52322816848754, 5.72411584854125, 5.93419885635375, 6.54741382598876, 6.19974613189697, 6.50538301467895, 6.63411617279052, 6.37891292572021, 6.4466528892517, 6.41508293151855, 6.43753099441528, 6.22002410888671, 6.89802598953247, 7.60971117019653, 7.28835582733154, 7.94310188293457, 8.37616157531738, 8.23695755004882, 7.87959098815917, 7.10137605667114, 6.95530700683593, 7.09829807281494, 6.95363092422485, 7.24957799911499, 7.29469108581542, 7.37636995315551, 7.44855403900146, 7.2392520904541, 7.32921123504638, 7.13970518112182, 7.47422885894775, 7.03317403793334, 6.88645505905151, 6.88782119750976, 7.21643209457397, 7.0685977935791, 6.93829584121704, 6.53668785095214, 6.18062496185302, 5.81682586669921, 5.45015096664428, 5.81814908981323, 6.13027286529541, 6.34707784652709, 6.34743690490722, 6.19436883926391, 4.9771981239

---
### Exercise 20

1.	How many wind speed records/entries do we have? How might we find this out from the List we’ve just created.
2.	What is the average Wind Speed recorded in these data? Hint: You may find the `sum` function useful here.
3.	What is the minimum Wind Speed? (Hint: `max( some_list )`)
4.	What is the maximum Wind Speed? (Hint: `min( some_list )`)

---

In [49]:
print(len(speed))
print(sum(speed)/len(speed))
print(max(speed))
print(min(speed))

50530
7.557952236083209
25.2060108184814
0.0


---
### Exercise 21
Using a new Context Manager, this time set for write mode. Create a CSV Writer, and write out your Wind Speed List you created in Ex18.

View this file in a notepad (or Notepad++) to verify.

---

In [56]:
import csv
with open('example.csv', mode='a') as my_csv_file:
    csv_writer = csv.writer(my_csv_file, delimiter=',')
    csv_writer.writerow(speed)

---
## Small Introduction to Numpy
### Exercise 22
Numpy is used for numerical computing, and allows us to convert from Lists to Numpy Arrays. These types have some useful functionality defined on them!

Have a look at the following code. Numpy arrays behave very similarly to Python standard Lists; however, they have more defined functions available to them for computational purposes. Previously you had to create an expression to get the summation and then the length and calculate the mean. Numpy has a function to do this. Remember: Functions are useful for utilities and routines we may often require. Therefore, numpy bundled a lot of these as behaviours on their own Data Type numpy `ndarray`.

For scientific computing, Numpy is written with several optimisations in mind. This makes it significantly faster for calculating on large sets of data.
```
import numpy as np # Just an alias, I type np instead of numpy
x = np.array( speed )
print( type(speed) )
print( type(x) )

print(x[0] == speed[0]) # Standard Indexing. So far equivalent in how we use them!
print(x[-1] == speed[-1]) # Reverse Indexing.

# useful statistics
print("Mean:", x.mean() )
print("Max:", x.max() )
print("Min:", x.min() )

# More complex statistical measures of spread/dispersion
print(x.std()) # Standard Deviation
print(x.var()) # Variance = std ** 2
try:
	print(mean(speed)) # Try either of these.
	#print(speed.mean())
except Exception as e:
	print(e)
```

---

In [57]:
import numpy as np
x = np.array(speed)
print( type(speed) )
print( type(x) )

<class 'list'>
<class 'numpy.ndarray'>


---
## JSON Read/Write
### Exercise 23
Recall Davey McDuck from this week’s lectures. I have decided to add a new data attribute for our ducks, the number of people they follow on twitter. This is known as ‘following’.
```
duck_1 = {
	"first_name": "Davey",
	"last_name": "McDuck",
	"location": "Rob's Office",
	"insane": True,
	"followers": 12865,
	"following": 120,
	"weapons": ["wit", "steely stare", "devilish good looks"],
	"remorse": None
}
```
Let’s build up our duck collection. We can represent this as a List of Dictionaries. Where each Dictionary follows the same pattern for outlining a Duck. First let’s define some ducks. Feel free to add your own!
```
duck_2 = {
	"first_name": "Jim",
	"last_name": "Bob",
	"location": "Turing Lab",
	"insane": False,
	"followers": 123,
	"following": 5000,
	"weapons": ["squeak"],
	"remorse": None
}

duck_3 = {
	"first_name": "Celest",
	"last_name": "",
	"location": "Throne Room",
	"insane" : True,
	"followers": 40189,
	"following": 1, # Her other account
	"weapons": ["politics", "dance moves", "chess grandmaster", "immortality"]
}
``` 

We shall put these in a List called duck_collection
```
duck_collection = [ duck_1, duck_2, duck_3 ]
```
Go through the `duck_collection`, and make sure each element is in-place and all your ducks are accounted for.

---

In [1]:
duck_1 = {
    "first_name": "Davey",
    "last_name": "McDuck",
    "location": "Rob's Office",
    "insane": True,
    "followers": 12865,
    "following": 120,
    "weapons": ["wit", "steely stare", "devilish good looks"],
    "remorse": None
}

duck_2 = {
    "first_name": "Jim",
    "last_name": "Bob",
    "location": "Turing Lab",
    "insane": False,
    "followers": 123,
    "following": 5000,
    "weapons": ["squeak"],
    "remorse": None
}

duck_3 = {
    "first_name": "Celest",
    "last_name": "",
    "location": "Throne Room",
    "insane" : True,
    "followers": 40189,
    "following": 1,
    "weapons": ["politics", "dance moves", "chess grandmaster", "immortality"]
}

duck_collection = [duck_1, duck_2, duck_3]

for x in range(len(duck_collection)):
    print(duck_collection[x])


{'first_name': 'Davey', 'last_name': 'McDuck', 'location': "Rob's Office", 'insane': True, 'followers': 12865, 'following': 120, 'weapons': ['wit', 'steely stare', 'devilish good looks'], 'remorse': None}
{'first_name': 'Jim', 'last_name': 'Bob', 'location': 'Turing Lab', 'insane': False, 'followers': 123, 'following': 5000, 'weapons': ['squeak'], 'remorse': None}
{'first_name': 'Celest', 'last_name': '', 'location': 'Throne Room', 'insane': True, 'followers': 40189, 'following': 1, 'weapons': ['politics', 'dance moves', 'chess grandmaster', 'immortality']}


---
### Exercise 24

1.	`import json`
2.	Using a context manager, open a json file for writing
3.	Using `json.dump`, write your `duck_collection to the file you’ve opened. Remember that the arguments are almost backwards from what we’re used to!

Open the file and we can copy its contents, which are rather unreadable at the moment, and use a pretty printing website to make it a bit easier on the eyes.

Paste your file contents into https://jsonformatter.org/json-pretty-print and see the output. Are all your ducks there? Do they all have their attributes?

---

In [3]:
import json

with open('example.json', mode="w") as example:
    json.dump(duck_collection, example)
    
with open('example.json', mode='r') as manifest:
    print( type(json.load(manifest)) )

<class 'list'>


---
### Exercise 25
Using `json.load`, load your saved json file back in, assigning the output to a new list variable (other than `duck_collection`). This should be identical to your `duck_collection`. We can check for this by checking the equivalence between both lists.

---

In [4]:
import json

    
with open('example.json', mode='r') as example:
    example_list = json.load(example)
    
if example_list == duck_collection:
    print("equal!")


equal!


---
### Exercise 26
Write some code which, for each duck, will calculate the difference between the number of people following them and the number of followers of their twitter account. (Positive if more people follow them, than they follow).

1.	Print these
2.	Append them to an empty list called `trendy_ducks`

E.g. for Davey, this would be his “followers” minus his “following” value. In this case 12865 - 120 = 12745. Note: This should be done programmatically! I might give you many more ducks. I want these resultant numbers for ALL ducks.

Hint: How do we index dictionaries? `some_dict["key"]` should give us the value. Our List we just got from `json.load` has a dictionary at every index of our List (Nested structures here).

> 12745  
-4877  
40188  
Trendy Ducks: [12745, -4877, 40188]

---

In [6]:
trendy_ducks = []
for duck in range(len(duck_collection)):
    trendy = duck_collection[duck]["followers"] - duck_collection[duck]["following"]
    print(trendy)
    trendy_ducks.append(trendy)
print("Trendy ducks:", trendy_ducks)

12745
-4877
40188
Trendy ducks: [12745, -4877, 40188]


---
### Exercise 27

Numpy has some useful functionality. If I wanted to find the trendiest duck (the one with the most ‘net’ followers (followers - following), I could use max or min. But this gives me the value back out, not necessarily which duck this relates to! I wanted an index so I could track the duck down.

Convert the `trendy_ducks` list to a numpy array
```
arr_trendy_ducks = np.array(trendy_ducks)
```
We can now call `argmax()` on this numpy ndarray object (or `argmin()` too) to show which duck has the most (or least).
```
print( arr_trendy_ducks.argmax() )
```
If I assign a variable to that function call, I now have the index of the trendiest duck. I can use this to go back to my original `duck_collection` List, which houses each duck dictionary, and pull things like their name.

__Print the first name of the trendiest duck, programmatically, and print out their ‘net’ following count (the thing you calculated!).__

No manual entry here. This code should work directly off of the List collection, so that I can add more ducks and your code would work exactly the same, and maybe a new Duck is crowned champion.

Hint: `duck_collection[0]` would get our first duck. We can replace 0 with any variable, so long as it returns an integer. `duck_collection[0]` would return a whole dictionary related to that duck. We can then reference the keys within that dictionary!
```
duck_collection[0]["some_key"]
```
Hint 2: You may need to cast the net followers! Numpy likes to use it’s own primitive data types for numbers. You will see :)

> __Congratulations Celest. You are the trendiest duck!  
> You have a net following of 40188 followers!

---

In [10]:
import numpy as np
arr_trendy_ducks = np.array(trendy_ducks)
maximum_duck = arr_trendy_ducks.argmax()
print("Congratulations"+ " " + duck_collection[maximum_duck]["first_name"] + "You are the trendiest duck! You have a net following of", duck_collection[maximum_duck]["followers"], "followers" )

Congratulations CelestYou are the trendiest duck! You have a net following of 40189 followers


---
### Exercise 28
Your boss has given you the task of creating a separate JSON file. In this file, he only wants ducks who have a net follower count > 0. 
You must filter out the ducks who follow more accounts than who follow them, and save these ducks back out to a JSON file just like your input was.

1.	Reusing your net follower calculations find indices of all the ducks you need.
2.	Store them in a separate data structure (create this, and add the correct ducks using the indices found)
3.	Open a new file in write mode to put this JSON data into. (Use a context manager).
4.	Use `json.dump` to convert your separate data structure into JSON and store it in the file.

This exercise will involve a lot of juggling of variables, and data structures, and logic. Values and Indices will need to be managed appropriately. Try doing this before moving onto Ex 29, where we’ll look at a nice feature of Numpy which might be more helpful.

---

In [14]:
import json

new_ducks_indices = []
for duck in range(len(trendy_ducks)):
    if trendy_ducks[duck] > 0:
        new_ducks_indices.append(duck)
        
with open('new_json.json', mode="w") as duck:
    new_json = []
    for x in range(len(new_ducks_indices)):
        new_json.append(duck_collection[x])
    json.dump(new_json, duck)

with open('new_json.json', mode='r') as manifest:
    print( type(json.load(manifest)) )
        

<class 'list'>


---
### Exercise 29

Numpy provides some functionality outside of just its objects. (https://numpy.org/doc/stable/reference/generated/numpy.where.html)
```
np.where( expression )
```
This returns a `ndarray` of indices where the expression holds True. For example, we can provide a whole array of values, and an expression which can be used to filter it. Numpy will then not only find where the condition is True or False, but then convert those into indices and provide them.

E.g.  
We can find all the indices of ducks, where their “net follower” count is even.
```
arr_trendy_ducks % 2 == 0
```
Normally we would pass an integer/number to this expression. However, with numpy arrays it can be applied to every value. If we print the output of this expression, we should get a List of True/False, where the condition holds!

We can pass this True/False List into `np.where()` and it will convert those into the indices for us.

Putting it together:
```
#Ex 29
print(arr_trendy_ducks % 2 == 0)

print(np.where(arr_trendy_ducks % 2 == 0))
```
> __[False False True]  
(array([2]),)__

This has returned a tuple. Remember, a tuple is defined as `(item, item, item)`. The trick here is that it’s a single element, you can see by the trailing comma. To get the actual array/List which contains the indices you’ll need to call `[0]` on the `np.where` result.
Note: If we wanted to convert a numpy array back into a List, we can cast it just like we did with numbers weeks ago.
```
actual_indices = np.where(arr_trendy_ducks % 2 == 0)[0]
print(actual_indices)
print(type(actual_indices))
print(type(list(actual_indices)))
```
> __[2]  
<class 'numpy.ndarray'>  
<class 'list'>__

_Technical Explanation: In our toy example here, we’re using a single dimension (List of numbers). But np.where is very powerful and can actually be run over N-dimensional data. Therefore each entry in the tuple is a dimension. As we only have 1, we get a single one back._

As we can see, only one of our ducks has an even count. This is the duck at index 2. Surprise, surprise, this is Celest again.

 

---

In [18]:
print(arr_trendy_ducks % 2 == 0)

actual_indices = np.where(arr_trendy_ducks % 2 == 0)[0]
print(actual_indices)
print(type(actual_indices))
print(type(list(actual_indices)))

[False False  True]
[2]
<class 'numpy.ndarray'>
[2]


---
### Exercise 30
Copy your answer to Ex 28, and now use the `np.where` from Ex 29 to make your solution tidier, cleaner, more readable. In my example I did a boolean expression for even numbers, you need to find those > 0.

Hint: The array you get back, contains elements which are the index to look-up. A list comprehension is a perfect choice here. It sounds complicated, but it’s just a List of indices you want to go through, and use them to reference the right ducks. Making a new list out of them. 

> [{'first_name': 'Celest',  
  'insane': True,  
  'followers': 40189,  
  'following': 1,  
  'weapons': ['politics', 'dance moves', 'chess grandmaster', 'immortality']}]
  

 
---

In [20]:
ducks_indices = np.where(arr_trendy_ducks % 2 > 0)[0]
print(ducks_indices)
new_ducks_with_indices = []
for x in ducks_indices:
    new_ducks_with_indices.append(duck_collection[x])
    
print(new_ducks_with_indices)

[0 1]
[{'first_name': 'Davey', 'last_name': 'McDuck', 'location': "Rob's Office", 'insane': True, 'followers': 12865, 'following': 120, 'weapons': ['wit', 'steely stare', 'devilish good looks'], 'remorse': None}, {'first_name': 'Jim', 'last_name': 'Bob', 'location': 'Turing Lab', 'insane': False, 'followers': 123, 'following': 5000, 'weapons': ['squeak'], 'remorse': None}]


__The Extended Exercises are optional, and are offered as an advanced supplement for those who have completed the existing work and wish to expand on their knowledge and challenge themselves further.__

---

### There is no extended exercise this week

This workshop is considered lengthy, and conceptually difficult enough as-is. If you do wish to learn more, after completing EVERYTHING, feel free to dive deeper into Numpy.

Create more ducks, make a duck army.
Use random number generators to generate this duck army. Numbers will be easy, but what about weapons? Maybe you want to sample the duck’s weapons from a predefined list of weapons (an armory of sorts).

For more advanced data mocking, we have a library called `faker` which can do more than simple random ranges, but distributions, names, places, etc.

There is nothing stopping you now, you’ve learned Python syntax, as we continue you’re just adding more to the knowledge you have. Play around with things, go crazy.

